-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.challenge DROP CONSTRAINT IF EXISTS challenge_game_id_fkey;

ALTER TABLE IF EXISTS public.challenge_vote DROP CONSTRAINT IF EXISTS challenge_vote_challenge_id_fkey;

ALTER TABLE IF EXISTS public.challenge_vote DROP CONSTRAINT IF EXISTS challenge_vote_user_id_fkey;

ALTER TABLE IF EXISTS public.participation DROP CONSTRAINT IF EXISTS participation_challenge_id_fkey;

ALTER TABLE IF EXISTS public.participation DROP CONSTRAINT IF EXISTS participation_user_id_fkey;

ALTER TABLE IF EXISTS public.participation_vote DROP CONSTRAINT IF EXISTS participation_vote_participation_id_fkey;

ALTER TABLE IF EXISTS public.participation_vote DROP CONSTRAINT IF EXISTS participation_vote_user_id_fkey;

ALTER TABLE IF EXISTS public.password_reset_token DROP CONSTRAINT IF EXISTS password_reset_token_user_id_fkey;

ALTER TABLE IF EXISTS public."user" DROP CONSTRAINT IF EXISTS user_role_id_fkey;

DROP TABLE IF EXISTS public.challenge;

CREATE TABLE IF NOT EXISTS public.challenge
(
    challenge_id uuid NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    rules text COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    game_id uuid NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    image_url text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    CONSTRAINT challenge_pkey PRIMARY KEY (challenge_id)
);

DROP TABLE IF EXISTS public.challenge_vote;

CREATE TABLE IF NOT EXISTS public.challenge_vote
(
    challenge_vote_id uuid NOT NULL,
    user_id uuid NOT NULL,
    challenge_id uuid NOT NULL,
    CONSTRAINT challenge_vote_pkey PRIMARY KEY (challenge_vote_id)
);

DROP TABLE IF EXISTS public.game;

CREATE TABLE IF NOT EXISTS public.game
(
    game_id uuid NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    release_date timestamp(6) without time zone NOT NULL,
    image_url text COLLATE pg_catalog."default",
    platform text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT game_pkey PRIMARY KEY (game_id)
);

DROP TABLE IF EXISTS public.participation;

CREATE TABLE IF NOT EXISTS public.participation
(
    participation_id uuid NOT NULL,
    user_id uuid NOT NULL,
    video_url text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default" NOT NULL,
    challenge_id uuid NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT participation_pkey PRIMARY KEY (participation_id)
);

DROP TABLE IF EXISTS public.participation_vote;

CREATE TABLE IF NOT EXISTS public.participation_vote
(
    participation_vote_id uuid NOT NULL,
    user_id uuid NOT NULL,
    participation_id uuid NOT NULL,
    CONSTRAINT participation_vote_pkey PRIMARY KEY (participation_vote_id)
);

DROP TABLE IF EXISTS public.password_reset_token;

CREATE TABLE IF NOT EXISTS public.password_reset_token
(
    token_id uuid NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp(3) without time zone NOT NULL,
    create_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id uuid NOT NULL,
    CONSTRAINT password_reset_token_pkey PRIMARY KEY (token_id)
);

DROP TABLE IF EXISTS public."user";

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id uuid NOT NULL,
    pseudonym text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    avatar_url text COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    role_id integer NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (user_id)
);

DROP TABLE IF EXISTS public.user_role;

CREATE TABLE IF NOT EXISTS public.user_role
(
    id uuid NOT NULL,
    role_id integer NOT NULL DEFAULT 0,
    role_name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(3) without time zone,
    updated_at timestamp(3) without time zone,
    CONSTRAINT user_role_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.challenge
    ADD CONSTRAINT challenge_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.game (game_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.challenge_vote
    ADD CONSTRAINT challenge_vote_challenge_id_fkey FOREIGN KEY (challenge_id)
    REFERENCES public.challenge (challenge_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.challenge_vote
    ADD CONSTRAINT challenge_vote_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.participation
    ADD CONSTRAINT participation_challenge_id_fkey FOREIGN KEY (challenge_id)
    REFERENCES public.challenge (challenge_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.participation
    ADD CONSTRAINT participation_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.participation_vote
    ADD CONSTRAINT participation_vote_participation_id_fkey FOREIGN KEY (participation_id)
    REFERENCES public.participation (participation_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.participation_vote
    ADD CONSTRAINT participation_vote_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.password_reset_token
    ADD CONSTRAINT password_reset_token_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT user_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.user_role (role_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

END;